[package]
name = "gkquad"
version = "0.0.1"
authors = ["Kogia-sima <orcinus4627@gmail.com>"]
license = "GPL-3.0-or-later"
homepage = "https://github.com/Kogia-sima/gkquad-rs"
repository = "https://github.com/Kogia-sima/gkquad-rs"
readme = "../README.md"
keywords = ["math", "numerics"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "gkquad"
path = "src/lib.rs"
test = false
doctest = false

[features]
default = ["std", "single"]
single = []
std = []

[dependencies]
smallvec = "1.2.0"
